// Auth
export 'auth/login_screen.dart';
// Home
export 'home/home_screen.dart';
// Inventario
export 'inventory/inventory_screen.dart';
// Catalogo
export 'catalog/catalog_screen.dart';
// Scanner
export 'scanner/take_picture_screen.dart';
